env:
  node: true
  es2021: true
  jest: true
extends: airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: 
  no-console: 0
  import/extensions: # FIXME: remove when rule will be adjusted for new nodejs version
    - error
    - ignorePackages
    - js: always
  no-confusing-arrow: [
    "error",
    { "allowParens": true, "onlyOneSimpleParam": true }
  ]
  no-param-reassign: [
    "error",
    {
      "props": true,
      "ignorePropertyModificationsFor": ["accu"]
    }
  ],
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }] # allow doubled underline for two constants
  linebreak-style: 0 
