name: main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
        # Check-out repository under GitHub workspace
        # https://github.com/actions/checkout
      - uses: actions/checkout@v3

      - run: make install
      - run: make lint